on:
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
  schedule:
    - cron: 0 * * * *
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denolib/setup-deno@v2
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v2
        with:
          http_url: https://www.oref.org.il/Shared/Ajax/GetAlarmsHistory.aspx?lang=he&mode=0
          downloaded_filename: temp-data.json
          postprocess: ./postprocess.ts